import { Inter } from "next/font/google";
import Navbar from "../Components/Shared/Navbar";
import Footer from "@/Components/Shared/Footer";
import Layout from "@/Components/Shared/Layout";
import Head from "next/head";

import "../globals.css";
// import image from "../../lib/assets"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Papercycle.in | Odisha's 1st and leading digital recycling platform.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
          {/* <link rel="shortcut icon" href={favicon} /> */}
          <link rel="shortcut icon" type="image/png" href="./icon.png" />
        </Head>
      <body className={inter.className}>
        <Layout>
          <Navbar />
          <div className="px-12 md:max-w-screen-xl m-auto">{children}</div>
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
